
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install TruffleHog via APT
      apt:
        name: trufflehog
        state: present

    - name: Verify TruffleHog installation
      command: trufflehog --help
      register: trufflehog_output
      failed_when: trufflehog_output.rc != 0
      changed_when: false

    - name: Output TruffleHog help
      debug:
        msg: "{{ trufflehog_output.stdout }}"
