
    - name: Install pipx using apt
      apt:
        name: pipx
        state: present
        update_cache: yes

    - name: Install Shodan using pipx
      command: pipx install shodan

    - name: Verify Shodan installation
      command: shodan --help
      register: shodan_output
      failed_when: shodan_output.rc != 0
      changed_when: false

    - name: Output Shodan help
      debug:
        msg: "{{ shodan_output.stdout }}"
