
    - name: Install python3-pip using apt
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    # Устанавливаем Shodan CLI с помощью pip3
    - name: Install Shodan CLI via pip
      pip:
        name: shodan
        executable: /usr/bin/pip3

    # Проверяем установку Shodan CLI
    - name: Verify Shodan CLI installation
      command: /usr/bin/shodan --help
      register: shodan_output
      failed_when: shodan_output.rc != 0
      changed_when: false

    # Выводим результат установки
    - name: Output Shodan CLI help
      debug:
        msg: "{{ shodan_output.stdout }}"
